[package]
name = 'datefixR'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'datefixR'

[dependencies]
extendr-api = { version = "*", default-features = false, features = ["result_condition"] }
regex = "1.5"
chrono = "0.4"
lazy_static = "1.4"
