on: 
  push:
    branches: [master, main]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install shiny
        run: |
          install.packages(c("curl", "shiny", "rsconnect", "remotes", "pkgbuild")); remotes::install_deps(dependencies = TRUE) 
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          rsconnect::setAccountInfo(name='nathansam', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}}); rsconnect::deployApp(appName = 'datefixr', forceUpdate = TRUE) 
        shell: Rscript {0}