on: 
  push:
    branches: [master, main]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect", "remotes"), type = "binary"); remotes::install_deps(dependencies = TRUE) 
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='nathansam', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'datefixr')" 